### ISSUE TITLE
Request for RUBY

### ISSUE THREAD

**Issue by spa5k** [webinstall/webi-installer-requests#111]

**Comment by coolaj86** [comment]
This is soooo hard.

Surprisingly Ruby does not offer official builds of any kind, and there is no clear winner in the version management space - and the compatibility matrix between Mac, Linux, and Windows for version managers is not good. 

I was just playing around with it this week and I think right now things are worse than they've ever been.

I think we need to wait for macOS to drop the native ruby and reinvestigate afterwards.

I'd love to have Ruby, but I personally don't know what the automated process should look like. I'm open to suggestions if you know of a clear win.

**Comment by ascarter** [comment]
@coolaj86 I suggest using `rbenv` instead of Ruby itself. This would be more analogous to `rustup`. I use this in my own dotfiles scripts:

```
# Ruby
echo "Configuring Ruby (rbenv)"
curl -fsSL https://rbenv.org/install.sh | bash
```

References:
https://rbenv.org

This script will:
* On macOS with Homebrew installed, install `rbenv` and `ruby-build` using Homebrew
* On Linux or without Homebrew, it will `git clone` rbenv and ruby-build
* rbenv uses ruby-build to compile Ruby for you.

Short answer as an active Rubyist, the best methods these days are to use something like this. I don't think it is common to install Ruby via package manager. So don't both with Ruby - just package up rbenv and speaking as a Ruby developer, you would this code off my shoulders in my dotfiles :)

I take a look at making a pull request to do it once I wrap my head around webinstall.
